### ISSUE TITLE
schema.yaml 변경 후에 Job의 restartPolicy가 always로 설정되는 버그

### ISSUE THREAD

**Issue by JunhoeKim** [onetop21/cerberus-document-editor#15]
바꾼 schema.yaml

```yaml
    deployment:
      <<: *metadata
      workspace:
        type: dict
        required: true
        selector:
          workspace: *workspace
          buildscript: *buildscript
          dockerfile: *dockerfile
        order: 10
        description: Workspace specs to build project.
      ingress:
        type: dict
        required: false
        keysrules:
          type: string
          regex: "^([a-z]+[a-z0-9\\-]*[a-z0-9]+|[a-z0-9])$"
        valuesrules:
          type: dict
          schema: *ingress
        order: 20
        description: Ingress specs to expose apps.
      app:
        type: dict
        keysrules:
          type: string
          regex: "^([a-z]+[a-z0-9\\-]*[a-z0-9]+|[a-z0-9])$"
        valuesrules:
          type: dict
          selector:
            job: *job
            service: *service
        order: 30
        description: Apps to run.
```

문제가 되는 yaml
```yaml
kind: Deployment
apiVersion: v1
name: example
version: 0.0.1
maintainer: root
workdir: .
workspace:
  kind: Workspace
  base: python:latest
  preps:
  - pip: requirements.txt
  ignores:
  - '**/.*'
  env:
    PYTHONUNBUFFERED: '1'
ingress:
  server-ingress:
    target: server:5555
    rewritePath: true
app:
  server:
    kind: Job
    command: python server.py
    ports:
    - 5555
    scale: 1
    mounts:
    - mountPath: mlad/mnt
      path: .
      options:
      - soft
      - timeo=30
      - retry=5
    quota:
      gpu: 1
  client:
    kind: Job
    command: python client.py
    ports:
    - 5555
    scale: 1

```

밑의 client의 restartPolicy default 값이 always가 되는 버그가 있습니다.
